### ISSUE TITLE
Crash in PrismicDOM.RichText.asHtml() with Media embeds

### ISSUE THREAD

**Issue by cb-fred** [prismicio/prismic-dom#10]
Hi, I am having an issue with PrismicDOM when rendering documents that have Media Embeds (such as youtube videos)

Here is a test case that reproduces the issue. The RichText data comes from the Prismic.io v2 API.

```javascript
var PrismicDOM = require('prismic-dom');

var text = [{"type":"heading3","text":"Foobar","spans":[]},{"type":"embed","oembed":{"type":"video","embed_url":"https://www.youtube.com/watch?v=Xlf2G0O_VY0","title":"I'm Fired, Aren't I? (The Simpsons)","provider_name":"YouTube","thumbnail_url":"https://i.ytimg.com/vi/Xlf2G0O_VY0/hqdefault.jpg","height":344,"author_name":"ThingsICantFindOtherwise","author_url":"https://www.youtube.com/channel/UCm6CzMdSu3zaGfjs9yTcUsQ","width":459,"thumbnail_height":360,"provider_url":"https://www.youtube.com/","thumbnail_width":480,"html":"<iframe width=\"459\" height=\"344\" src=\"https://www.youtube.com/embed/Xlf2G0O_VY0?feature=oembed\" frameborder=\"0\" allowfullscreen></iframe>","version":"1.0"}}];

var html = PrismicDOM.RichText.asHtml(text);

console.log(html);
```
The output of this test case when running it with node.js v8.4.0 is the following:

```bash
TypeError: Cannot read property 'length' of undefined
    at i (/Users/fred/Documents/Code/prismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:4734)
    at /Users/fred/Documents/Code/prismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:6907
    at Array.reduce (<anonymous>)
    at Function.e.fromRichText (/Users/fred/Documents/Code/prismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:6850)
    at Object.r [as serialize] (/Users/fred/Documents/Code/prismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:14368)
    at Object.asHtml (/Users/fred/Documents/Code/prismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:3938)
    at Object.<anonymous> (/Users/fred/Documents/Code/prismic/index.js:5:32)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
``` 

I have the same issue in latest Chrome. 
The version of the PrismicDOM library installed is `2.0.0`

**Comment by arnaudlewis** [comment]
Hi @cb-fred, you probably have made a mistake because this JSON is the format of api v1, not v2, that's why it's not working.

**Comment by slavafomin** [comment]
I'm having the same issue, the rich text, which is causing the problem is this:

```json
[
    {
        "type": "embed",
        "oembed": {
            "type": "video",
            "embed_url": "https://vimeo.com/184822405/62a33fd6eb",
            "title": "Марина Коваль - \"Я-бренд. Искусство презентации на сцене и в жизни\" веби",
            "provider_name": "Vimeo",
            "thumbnail_url": null,
            "version": "1.0",
            "provider_url": "https://vimeo.com/",
            "html": "<iframe src=\"https://player.vimeo.com/video/184822405\" width=\"640\" height=\"360\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>",
            "width": 640,
            "height": 360,
            "video_id": 184822405,
            "uri": "/videos/184822405:62a33fd6eb"
        }
    }
]
```

What can be done about it?

**Comment by arnaudlewis** [comment]
@slavafomin same issue here, prismic-dom is meant for api v2, not v1 so you can either upgrade to api v2 and follow the official documentation to migrate your code or just use the javascript kit for v1 instead (npm install prismic.io).

**Comment by cb-fred** [comment]
How do we get Api V2 ? Isn't appending `v2` to the api url sufficient ? Or is there some settings in the project that I have missed ? I still get issues with the following code

```
var PrismicDOM = require('prismic-dom');
var Prismic = require('prismic-javascript');

Prismic.getApi('https://codabox.prismic.io/api/v2').then(function(api) {
    api.getByID('WbFCzCcAAISKBAiY').then(function(doc) {
        console.log(JSON.stringify(doc,null,4));
        console.log(PrismicDOM.RichText.asHtml(doc.data.body));
    });
})
```

(now it doesn't crash but I get unclosed string in tags)

```
<div data-oembed="undefined"
      data-oembed-type="embed"
      data-oembed-provider="undefined
      >
```
